### ISSUE TITLE
Теория JS

### ISSUE THREAD

**Issue by leszeof** [harryheman/JavaScript-Practice#5]
Здравствуйте! Хотел бы в первую очередь поблагодарить вас за ваш труд! 
Довольно долгое время практиковался на вашей платформе в теории и практики, но после очередного обновления пропала теория. Она была очень удобная так как есть формат "вопрос-ответ". Подскажите пожалуйста, не осталось ли исходников или может есть более полная версия?

**Comment by aimcode** [comment]
Здравствуйте, присоединяюсь к вопросу. Было очень удобно готовиться к собеседованию, а сегодня обнаружил что изменился дизайн и пропал раздел с теорией.
